export const ActionTypes = {

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_RESTART: "LOGIN_REQUEST_RESTART",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAILURE: "LOGIN_REQUEST_FAILURE",
  LOGIN_WITH_GOOGLE_REQUEST: "LOGIN_WITH_GOOGLE_REQUEST",
  LOGIN_WITH_GOOGLE_SUCCESS: "LOGIN_WITH_GOOGLE_SUCCESS",
  LOGIN_WITH_GOOGLE_FAILURE: "LOGIN_WITH_GOOGLE_FAILURE",
  LOG_OUT_REQUEST: "LOG_OUT_REQUEST",

  //REGISTER USER
  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

  FECTH_EVENT_REQUEST: "FECTH_EVENT_REQUEST",
  FECTH_EVENT_SUCCESS: "FECTH_EVENT_SUCCESS",
  FECTH_EVENT_FAILURE: "FECTH_EVENT_FAILURE",
  FECTH_EVENT_REMOVE: "FECTH_EVENT_REMOVE",

  SUBMIT_CONTACT_FORM_REQUEST: "SUBMIT_CONTACT_FORM_REQUEST",
  SUBMIT_CONTACT_FORM_SUCCESS: "SUBMIT_CONTACT_FORM_SUCCESS",
  SUBMIT_CONTACT_FORM_FAILURE: "SUBMIT_CONTACT_FORM_FAILURE",
  SUBMIT_CONTACT_FORM_RESET: "SUBMIT_CONTACT_FORM_RESET",

  ADD_TRANSACTION_REQUEST:"ADD_TRANSACTION_REQUEST" ,
  ADD_TRANSACTION_SUCCESS:"ADD_TRANSACTION_SUCCESS" ,
  ADD_TRANSACTION_FAILURE:"ADD_TRANSACTION_FAILURE" ,
  
  EDIT_TRANSACTION_REQUEST:"EDIT_TRANSACTION_REQUEST",
  EDIT_TRANSACTION_SUCCESS:"EDIT_TRANSACTION_SUCCESS",

  DELETE_TRANSACTION_REQUEST:"DELETE_TRANSACTION_REQUEST" ,
  DELETE_TRANSACTION_SUCCESS:"DELETE_TRANSACTION_SUCCESS" ,
  DELETE_TRANSACTION_FAILURE:"DELETE_TRANSACTION_FAILURE"
};